#! /bin/sh

# Copyright (C) 2018  Red Hat, Inc.
#
# This copyrighted material is made available to anyone wishing to use,
# modify, copy, or redistribute it subject to the terms and conditions of
# the GNU General Public License v.2, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY expressed or implied, including the implied warranties of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
# Public License for more details.  You should have received a copy of the
# GNU General Public License along with this program; if not, write to the
# Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.  Any Red Hat trademarks that are incorporated in the
# source code or documentation are not subject to the GNU General Public
# License and may only be used or replicated with the express permission of
# Red Hat, Inc.

workdir=$HOME/.cache/dnf-diff
mkdir -p "$workdir"

base=$1
filename=$2
rpmfile=$workdir/$base

die () { echo "FATAL: $*"; exit 1 ; }

case $filename in
    /*) ;;
    *) die "file '$filename' must be absolute" ;;
esac

test -f "$rpmfile" || die "not such file '$rpmfile'"
case $rpmfile in
    *.rpm) ;;
    *) die "not an rpm '$rpmfile'" ;;
esac

case $(file -i "$rpmfile") in
    *application/x-rpm*) ;;
    *) die "$rpmfile must be application/x-rpm file" ;;
esac

workdir=$HOME/.cache/dnf-diff

mkdir -p "$workdir"

cachedir=$workdir/${base%%.rpm}

test -d "$cachedir" || (
    mkdir -p "$cachedir"
    cd "$cachedir"
    rpm2cpio "$rpmfile" | cpio -idm &>/dev/null
)

(
    cd "$cachedir"
    diff -ru ".$filename" "$filename" \
        | sed '1s/--- \./--- /g'
)
